name: SMPPlugin
version: '${project.version}'
main: de.lostesburger.smp.smpplugin.Main
api-version: 1.20
author: "Lostes_Burger"
folia-supported: true
commands:
  tpa:

  tpaccept:

  endp:

  info:
    description: Get Information about the server

  disEnchant:
    description: Remove Item's elected enchantment
